### Test creating a new entry
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name": "Baz Murphy",
    "number": "44-987654321"
}

### Test creating with a missing name
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "number": "44-987654321"
}

### Test creating with a missing number
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name": "Baz Murphy"
}


### Test creating with a duplicat name
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name": "Dan Abramov",
    "number": "44-999999999"
}